BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[user_sync] (
    [id] INT NOT NULL IDENTITY(1,1),
    [email] NVARCHAR(1000) NOT NULL,
    [dataJson] NVARCHAR(max) NOT NULL,
    [synced_at] DATETIME2 NOT NULL CONSTRAINT [user_sync_synced_at_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [user_sync_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [user_sync_email_key] UNIQUE NONCLUSTERED ([email])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
